### ISSUE TITLE
Debug output of storage cp is full of error messages

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/platform-client-python#1887]
#### Description:
If you perform an upload to the storage with two `--verbose` flags, you won't be able to read the debug logs. (to debug your cp-exclude configurations, as in my case).

#### Example:
1. `touch test.txt`
2. `neuro --verbose --verbose storage cp test storage:test`
3. Observe error messages.

#### Expected behavior:
No error messages.

#### Additional context:
MacOS 10.15.7
Neuro Platform Client 20.12.2

**Comment by asvetlov** [comment]
I don't see "the log full of errors" but very verbose output

**Comment by YevheniiSemendiak** [comment]
Here's my console output:
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/32543098/101327329-36684980-3877-11eb-9e3d-0cbeb842efdc.png">

<details>
<summary> The full log of the `copy` command </summary>

(test) {20-12-07 10:29}ysem@ysem-macpro:~/work/projects/TMP|n --verbose storage cp test storage:test
asyncio.__init__: Using selector: KqueueSelector
asyncio.__init__: Using selector: KqueueSelector
neuromation.api.core.request: Fetch [GET] https://neuro-compute.org.neu.ro/api/v1/storage/yevheniisemendiak/test?op=GETFILESTATUS
asyncio._getaddrinfo_debug: Get address info neuro-compute.org.neu.ro:443, type=<SocketKind.SOCK_STREAM: 1>, flags=<AddressInfo.AI_ADDRCONFIG: 1024>
asyncio._getaddrinfo_debug: Get address info pypi.org:443, type=<SocketKind.SOCK_STREAM: 1>, flags=<AddressInfo.AI_ADDRCONFIG: 1024>
asyncio._getaddrinfo_debug: Getting address info neuro-compute.org.neu.ro:443, type=<SocketKind.SOCK_STREAM: 1>, flags=<AddressInfo.AI_ADDRCONFIG: 1024> took 3.617ms: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('40.76.158.45', 443))]
asyncio._getaddrinfo_debug: Getting address info pypi.org:443, type=<SocketKind.SOCK_STREAM: 1>, flags=<AddressInfo.AI_ADDRCONFIG: 1024> took 2.066ms: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('151.101.64.223', 443)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('151.101.128.223', 443)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('151.101.0.223', 443)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('151.101.192.223', 443))]
asyncio._start_handshake: <asyncio.sslproto.SSLProtocol object at 0x7fef6cec15b0> starts SSL handshake
asyncio._on_handshake_complete: <asyncio.sslproto.SSLProtocol object at 0x7fef6cec15b0>: SSL handshake took 33.3 ms
asyncio.create_connection: <asyncio.TransportSocket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.4', 53605), raddr=('151.101.64.223', 443)> connected to 151.101.64.223:443: (<asyncio.sslproto._SSLProtocolTransport object at 0x7fef6d1913a0>, <aiohttp.client_proto.ResponseHandler object at 0x7fef6d14f040>)
asyncio._start_handshake: <asyncio.sslproto.SSLProtocol object at 0x7fef6cea9ee0> starts SSL handshake
neuromation.cli.version_utils._fetch_package: 404 status on fetching https://pypi.org/pypi/neuro-cli/json
asyncio._on_handshake_complete: <asyncio.sslproto.SSLProtocol object at 0x7fef6cea9ee0>: SSL handshake took 278.7 ms
asyncio.create_connection: <asyncio.TransportSocket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.4', 53604), raddr=('40.76.158.45', 443)> connected to 40.76.158.45:443: (<asyncio.sslproto._SSLProtocolTransport object at 0x7fef6d212ac0>, <aiohttp.client_proto.ResponseHandler object at 0x7fef6d1bf400>)
Expand file:///Users/ysem/work/projects/TMP/test
[10:29:55] Copying /Users/ysem/work/projects/TMP/test => storage://neuro-compute/yevheniisemendiak/test
--- Logging error ---
Traceback (most recent call last):
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/log_formatter.py", line 34, in emit
    click.echo(msg, err=True)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/utils.py", line 272, in echo
    file.write(message)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/rich/progress.py", line 491, in write
    line, new_line, text = text.partition("\n")
TypeError: a bytes-like object is required, not 'str'
Call stack:
  File "/Users/ysem/opt/anaconda3/envs/test/bin/neuro", line 8, in <module>
    sys.exit(main())
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/main.py", line 537, in main
    cli.main(args=args, standalone_mode=False)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/utils.py", line 325, in invoke
    super().invoke(ctx)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/utils.py", line 325, in invoke
    super().invoke(ctx)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/utils.py", line 288, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/utils.py", line 105, in wrapper
    return root.run(
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/root.py", line 134, in run
    return self._runner.run(main)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/asyncio_utils.py", line 54, in run
    return self._loop.run_until_complete(main_task)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/asyncio/base_events.py", line 1851, in _run_once
    handle._run()
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/utils.py", line 77, in _run_async_function
    return await func(root, *args, **kwargs)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/storage.py", line 431, in cp
    await root.client.storage.upload_file(
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/api/storage.py", line 464, in upload_file
    dst_stat = await self.stat(dst)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/api/storage.py", line 321, in stat
    async with self._core.request("GET", url, auth=auth) as resp:
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/api/core.py", line 121, in request
    log.debug("Fetch [%s] %s", method, url)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/logging/__init__.py", line 1422, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/log_formatter.py", line 37, in emit
    self.handleError(record)
Message: 'Fetch [%s] %s'
Arguments: ('GET', URL('https://neuro-compute.org.neu.ro/api/v1/storage/yevheniisemendiak/test?op=GETFILESTATUS'))
--- Logging error ---
Traceback (most recent call last):
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/log_formatter.py", line 34, in emit
    click.echo(msg, err=True)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/utils.py", line 272, in echo
    file.write(message)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/rich/progress.py", line 491, in write
    line, new_line, text = text.partition("\n")
TypeError: a bytes-like object is required, not 'str'
Call stack:
  File "/Users/ysem/opt/anaconda3/envs/test/bin/neuro", line 8, in <module>
    sys.exit(main())
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/main.py", line 537, in main
    cli.main(args=args, standalone_mode=False)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/utils.py", line 325, in invoke
    super().invoke(ctx)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/utils.py", line 325, in invoke
    super().invoke(ctx)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/utils.py", line 288, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/utils.py", line 105, in wrapper
    return root.run(
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/root.py", line 134, in run
    return self._runner.run(main)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/asyncio_utils.py", line 54, in run
    return self._loop.run_until_complete(main_task)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/asyncio/base_events.py", line 1854, in _run_once
    logger.warning('Executing %s took %.3f seconds',
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/logging/__init__.py", line 1446, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/log_formatter.py", line 37, in emit
    self.handleError(record)
Message: 'Executing %s took %.3f seconds'
Arguments: ("<Task pending name='Task-1' coro=<_run_async_function() running at /Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/utils.py:77> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at
0x7fef6d15acd0>()] created at /Users/ysem/opt/anaconda3/envs/test/lib/python3.8/asyncio/base_events.py:422> cb=[_run_until_complete_cb() at /Users/ysem/opt/anaconda3/envs/test/lib/python3.8/asyncio/base_events.py:184] created at
/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/asyncio_utils.py:43>", 0.1646674130000001)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/api/storage.py", line 464, in upload_file
    dst_stat = await self.stat(dst)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/api/storage.py", line 321, in stat
    async with self._core.request("GET", url, auth=auth) as resp:
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/api/core.py", line 163, in request
    raise err_cls(err_text)
neuromation.api.errors.ResourceNotFound: 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/log_formatter.py", line 34, in emit
    click.echo(msg, err=True)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/utils.py", line 272, in echo
    file.write(message)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/rich/progress.py", line 491, in write
    line, new_line, text = text.partition("\n")
TypeError: a bytes-like object is required, not 'str'
Call stack:
  File "/Users/ysem/opt/anaconda3/envs/test/bin/neuro", line 8, in <module>
    sys.exit(main())
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/main.py", line 537, in main
    cli.main(args=args, standalone_mode=False)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/utils.py", line 325, in invoke
    super().invoke(ctx)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/utils.py", line 325, in invoke
    super().invoke(ctx)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/utils.py", line 288, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/utils.py", line 105, in wrapper
    return root.run(
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/root.py", line 134, in run
    return self._runner.run(main)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/asyncio_utils.py", line 54, in run
    return self._loop.run_until_complete(main_task)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/asyncio/base_events.py", line 1851, in _run_once
    handle._run()
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/utils.py", line 77, in _run_async_function
    return await func(root, *args, **kwargs)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/storage.py", line 431, in cp
    await root.client.storage.upload_file(
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/api/storage.py", line 470, in upload_file
    dst_parent_stat = await self.stat(dst.parent)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/api/storage.py", line 321, in stat
    async with self._core.request("GET", url, auth=auth) as resp:
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/api/core.py", line 121, in request
    log.debug("Fetch [%s] %s", method, url)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/logging/__init__.py", line 1422, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/log_formatter.py", line 37, in emit
    self.handleError(record)
Message: 'Fetch [%s] %s'
Arguments: ('GET', URL('https://neuro-compute.org.neu.ro/api/v1/storage/yevheniisemendiak?op=GETFILESTATUS'))
[10:29:56] Copying: /Users/ysem/work/projects/TMP/test
--- Logging error ---
Traceback (most recent call last):
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/log_formatter.py", line 34, in emit
    click.echo(msg, err=True)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/utils.py", line 272, in echo
    file.write(message)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/rich/progress.py", line 491, in write
    line, new_line, text = text.partition("\n")
TypeError: a bytes-like object is required, not 'str'
Call stack:
  File "/Users/ysem/opt/anaconda3/envs/test/bin/neuro", line 8, in <module>
    sys.exit(main())
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/main.py", line 537, in main
    cli.main(args=args, standalone_mode=False)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/utils.py", line 325, in invoke
    super().invoke(ctx)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/utils.py", line 325, in invoke
    super().invoke(ctx)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/utils.py", line 288, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/utils.py", line 105, in wrapper
    return root.run(
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/root.py", line 134, in run
    return self._runner.run(main)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/asyncio_utils.py", line 54, in run
    return self._loop.run_until_complete(main_task)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/asyncio/base_events.py", line 1851, in _run_once
    handle._run()
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/api/storage.py", line 917, in wrapped
    await coro
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/api/storage.py", line 521, in _upload_file
    await self.create(dst, chunk)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/api/storage.py", line 292, in create
    async with self._core.request(
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/api/core.py", line 121, in request
    log.debug("Fetch [%s] %s", method, url)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/logging/__init__.py", line 1422, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/log_formatter.py", line 37, in emit
    self.handleError(record)
Message: 'Fetch [%s] %s'
Arguments: ('PUT', URL('https://neuro-compute.org.neu.ro/api/v1/storage/yevheniisemendiak/test?op=CREATE'))
           Copied: /Users/ysem/work/projects/TMP/test

</details>

<details>
<summary> The list of installed Python packages </summary>
(test) {20-12-07 10:30}ysem@ysem-macpro:~/work/projects/TMP|pip list
Package           Version
----------------- -------------------
aiodocker         0.19.1
aiohttp           3.7.3
arrow             0.17.0
async-timeout     3.0.1
atomicwrites      1.4.0
attrs             20.3.0
binaryornot       0.4.4
certifi           2020.11.8
chardet           3.0.4
click             7.1.2
colorama          0.4.4
commonmark        0.9.1
cookiecutter      1.7.2
ecdsa             0.14.1
humanize          3.1.0
idna              2.10
Jinja2            2.11.2
jinja2-time       0.2.0
MarkupSafe        1.1.1
multidict         5.1.0
neuromation       20.12.2
pip               20.3
poyo              0.5.0
prompt-toolkit    3.0.8
pyasn1            0.4.8
Pygments          2.7.3
python-dateutil   2.8.1
python-jose       3.2.0
python-slugify    4.0.1
PyYAML            5.3.1
requests          2.25.0
rich              9.3.0
rsa               4.6
setuptools        50.3.2.post20201201
six               1.15.0
text-unidecode    1.3
toml              0.10.2
typing-extensions 3.7.4.3
urllib3           1.26.2
wcwidth           0.2.5
wheel             0.36.0
yarl              1.6.3
</details>


I've tried to replace this:
```
 File "/Users/ysem/opt/anaconda3/envs/test/lib/python3.8/site-packages/neuromation/cli/log_formatter.py", line 34, in emit
    click.echo(msg, err=True)
```
to `click.echo(bytes(msg, "utf-8"), err=True)`, but it didn't help.
What else could we investigate here?

**Comment by serhiy-storchaka** [comment]
Interesting. **rich** patches `sys.stderr`. **click** creates a wrapper for `sys.stderr`, but it thinks that `sys.stderr` is a binary file and wraps it into TextIOWrapper.

```
  click file = <_io.TextIOWrapper name='<stderr>' encoding='utf-8'>  0x7f7e56d29a00
  click file.buffer = <click._compat._FixupStream object at 0x7f7e55aa4f70>  0x7f7e55aa4f70
  click file.buffer.buffer = <_io.BufferedWriter name='<stderr>'>  0x7f7e59566e00
  click file.buffer.buffer.raw = <_io.FileIO name='<stderr>' mode='wb' closefd=False>  0x7f7e59579d80
```
As result the **rich** wrapper gets already encoded bytes as argument of write().

I take this issue.
