### ISSUE TITLE
`neuro blob rmbucket` does not work for imported buckets

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/platform-client-python#2389]
1. import external bucket into the system
2. try to remove it via `neuro blob rmbucket`
3. Observe the error `ERROR: Bucket blob:ysemendiak-test-standard not found`

<details>
<summary> example on `default` cluster </summary>

```
(neuro) {21-10-22 11:41}ysem@ysem-macpro:~/work/projects/TMP|n blob ls
n blob rmbublob:ysemendiak-test-standard-2
blob:/romanskurikhin/test-bucket
blob:ysemendiak-test-standard
blob:/alexeynaiden/test
blob:/natalygur/test-bucket-1
blob:ml-artifacts
blob:/admin/onprem
blob:ml-recipe-bone-age-dvc
blob:test
blob:/natalygur/test-bucket-2
(neuro) {21-10-22 11:41}ysem@ysem-macpro:~/work/projects/TMP|n blob rmbucket blob:ysemendiak-test-standard
ERROR: Bucket blob:ysemendiak-test-standard not found
Traceback (most recent call last):
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/neuro_cli/main.py", line 556, in main
    cli.main(**kwargs)
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/neuro_cli/utils.py", line 325, in invoke
    super().invoke(ctx)
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/neuro_cli/utils.py", line 325, in invoke
    super().invoke(ctx)
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/neuro_cli/utils.py", line 288, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/neuro_cli/utils.py", line 102, in wrapper
    return root.run(
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/neuro_cli/root.py", line 174, in run
    return self._runner.run(main)
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/neuro_cli/asyncio_utils.py", line 55, in run
    return self._loop.run_until_complete(main_task)
  File "/Users/ysem/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/neuro_cli/utils.py", line 74, in _run_async_function
    return await func(root, *args, **kwargs)
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/neuro_cli/blob_storage.py", line 355, in rmbucket
    bucket_id = await resolve_bucket(
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/neuro_cli/utils.py", line 503, in resolve_bucket
    bucket = await client.buckets.get(id_or_name, cluster_name)
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/neuro_sdk/buckets.py", line 1102, in get
    async with self._core.request("GET", url, auth=auth) as resp:
  File "/Users/ysem/miniconda3/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/Users/ysem/.local/pipx/venvs/neuro-cli/lib/python3.8/site-packages/neuro_sdk/core.py", line 167, in request
    raise err_cls(err_text)
neuro_sdk.errors.ResourceNotFound: Bucket blob:ysemendiak-test-standard not found
(neuro) {21-10-22 11:41}ysem@ysem-macpro:~/work/projects/TMP|n blob ls blob:ysemendiak-test-standard
List of blob://default/yevheniisemendiak/ysemendiak-test-standard:
(neuro) {21-10-22 11:43}ysem@ysem-macpro:~/work/projects/TMP|
```

</details>

#### Expected behavior:
Bucket is removed

#### Additional context:
Neuro Platform Client 21.9.3
platformbucketsapi:21.10.2

cc @romasku

**Comment by romasku** [comment]
`neuro blob rmbucket` command works with bucket name, not with bucket URI. 
The correct command is: `blob rmbucket ysemendiak-test-standard`

**Comment by romasku** [comment]
Though, an error message is not very informative. We have [issue](https://github.com/neuro-inc/platform-client-python/issues/2463) to support uris in such commands, so in the future both syntaxes will be correct.

**Comment by YevheniiSemendiak** [comment]
Got it, in this case, let's close this report.
